In [17]:
import requests
import json
import csv
import pandas as pd
from bs4 import BeautifulSoup
import pprint
import glob

import time                            # スリープを使うために必要
from selenium import webdriver
import chromedriver_binary # Webブラウザを自動操作する（python -m pip install selenium)
from selenium.webdriver.common.keys import Keys

import shutil
import os

pd.options.display.float_format = '{:.2f}'.format
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)

In [18]:
# driver = webdriver.Chrome() # Chromeを準備
# #driver = webdriver.Edge() # Edgeを準備
# driver.get('https://www.google.com/') # Googleを開く
# driver.maximize_window()
# time.sleep(3)                          # 5秒間待機
# driver.quit()

In [19]:
# # Chrome
# # 2005
# driver = webdriver.Chrome()            # Chromeを準備
# driver.get('https://www.e-stat.go.jp/stat-search/files?page=1&layout=datalist&toukei=00200561&tstat=000000330001&cycle=7&year=20050&month=0&tclass1=000000330001&tclass2=000000330004&tclass3=000000330005&stat_infid=000000331B13&result_back=1&tclass4val=0') # Googleを開く
# driver.maximize_window()

# dl_btn = driver.find_element_by_xpath("/html/body/div[1]/div/main/div[2]/section/div[2]/div/div/div[1]/section/section/div/div[1]/div/div[2]/a")
# dl_btn.click() # ダウンロードフォルダに格納される
# time.sleep(3)
# driver.quit()

In [20]:
# # Edge
# # 2005
# driver = webdriver.Edge(executable_path='msedgedriver.exe')
# driver.get('https://www.e-stat.go.jp/stat-search/files?page=1&layout=datalist&toukei=00200561&tstat=000000330001&cycle=7&year=20050&month=0&tclass1=000000330001&tclass2=000000330004&tclass3=000000330005&stat_infid=000000331B13&result_back=1&tclass4val=0') # Googleを開く
# driver.maximize_window()

# dl_btn = driver.find_element_by_xpath("/html/body/div[1]/div/main/div[2]/section/div[2]/div/div/div[1]/section/section/div/div[1]/div/div[2]/a")
# dl_btn.click() # ダウンロードフォルダに格納される
# time.sleep(3)
# driver.quit()

In [21]:
years = []
list_2000 = 'https://www.e-stat.go.jp/stat-search/files?page=1&layout=datalist&toukei=00200561&tstat=000000330001&cycle=7&year=20000&month=0&tclass1=000000330001&tclass2=000000330004&tclass3=000000330005&stat_infid=0000003319F0&result_back=1&tclass4val=0'
list_2001 = 'https://www.e-stat.go.jp/stat-search/files?page=1&layout=datalist&toukei=00200561&tstat=000000330001&cycle=7&year=20010&month=0&tclass1=000000330001&tclass2=000000330004&tclass3=000000330005&stat_infid=000000331A2B&result_back=1&tclass4val=0'
list_2002 = 'https://www.e-stat.go.jp/stat-search/files?page=1&layout=datalist&toukei=00200561&tstat=000000330001&cycle=7&year=20020&month=0&tclass1=000000330001&tclass2=000000330004&tclass3=000000330005&stat_infid=000000331A68&result_back=1&tclass4val=0'
list_2003 = 'https://www.e-stat.go.jp/stat-search/files?page=1&layout=datalist&toukei=00200561&tstat=000000330001&cycle=7&year=20030&month=0&tclass1=000000330001&tclass2=000000330004&tclass3=000000330005&stat_infid=000000331AA1&result_back=1&tclass4val=0'
list_2004 = 'https://www.e-stat.go.jp/stat-search/files?page=1&layout=datalist&toukei=00200561&tstat=000000330001&cycle=7&year=20040&month=0&tclass1=000000330001&tclass2=000000330004&tclass3=000000330005&stat_infid=000000331ADA&result_back=1&tclass4val=0'
list_2005 = 'https://www.e-stat.go.jp/stat-search/files?page=1&layout=datalist&toukei=00200561&tstat=000000330001&cycle=7&year=20050&month=0&tclass1=000000330001&tclass2=000000330004&tclass3=000000330005&stat_infid=000000331B13&result_back=1&tclass4val=0'
list_2006 = 'https://www.e-stat.go.jp/stat-search/files?page=1&layout=datalist&toukei=00200561&tstat=000000330001&cycle=7&year=20060&month=0&tclass1=000000330001&tclass2=000000330004&tclass3=000000330005&stat_infid=000000331D65&result_back=1&tclass4val=0'
list_2007 = 'https://www.e-stat.go.jp/stat-search/files?page=1&layout=datalist&toukei=00200561&tstat=000000330001&cycle=7&year=20070&month=0&tclass1=000000330001&tclass2=000000330004&tclass3=000000330005&stat_infid=000001158907&result_back=1&tclass4val=0'
list_2008 = 'https://www.e-stat.go.jp/stat-search/files?page=1&layout=datalist&toukei=00200561&tstat=000000330001&cycle=7&year=20080&month=0&tclass1=000000330001&tclass2=000000330004&tclass3=000000330005&stat_infid=000002209396&result_back=1&tclass4val=0'
list_2009 = 'https://www.e-stat.go.jp/stat-search/files?page=1&layout=datalist&toukei=00200561&tstat=000000330001&cycle=7&year=20090&month=0&tclass1=000000330001&tclass2=000000330004&tclass3=000000330005&stat_infid=000007370332&result_back=1&tclass4val=0'
list_2010 = 'https://www.e-stat.go.jp/stat-search/files?page=1&layout=datalist&toukei=00200561&tstat=000000330001&cycle=7&year=20100&month=0&tclass1=000000330001&tclass2=000000330004&tclass3=000000330005&stat_infid=000008635831&result_back=1&tclass4val=0'
list_2011 = 'https://www.e-stat.go.jp/stat-search/files?page=1&layout=datalist&toukei=00200561&tstat=000000330001&cycle=7&year=20110&month=0&tclass1=000000330001&tclass2=000000330004&tclass3=000000330005&stat_infid=000012687873&result_back=1&tclass4val=0'
list_2012 = 'https://www.e-stat.go.jp/stat-search/files?page=1&layout=datalist&toukei=00200561&tstat=000000330001&cycle=7&year=20120&month=0&tclass1=000000330001&tclass2=000000330004&tclass3=000000330005&stat_infid=000019023723&result_back=1&tclass4val=0'
list_2013 = 'https://www.e-stat.go.jp/stat-search/files?page=1&layout=datalist&toukei=00200561&tstat=000000330001&cycle=7&year=20130&month=0&tclass1=000000330001&tclass2=000000330004&tclass3=000000330005&stat_infid=000023621378&result_back=1&tclass4val=0'
list_2014 = 'https://www.e-stat.go.jp/stat-search/files?page=1&layout=datalist&toukei=00200561&tstat=000000330001&cycle=7&year=20140&month=0&tclass1=000000330001&tclass2=000000330004&tclass3=000000330005&stat_infid=000028352467&result_back=1&tclass4val=0'
list_2015 = 'https://www.e-stat.go.jp/stat-search/files?page=1&layout=datalist&toukei=00200561&tstat=000000330001&cycle=7&year=20150&month=0&tclass1=000000330001&tclass2=000000330004&tclass3=000000330005&stat_infid=000031370133&result_back=1&tclass4val=0'
list_2016 = 'https://www.e-stat.go.jp/stat-search/files?page=1&layout=datalist&toukei=00200561&tstat=000000330001&cycle=7&year=20160&month=0&tclass1=000000330001&tclass2=000000330004&tclass3=000000330005&stat_infid=000031534696&result_back=1&tclass4val=0'
list_2017 = 'https://www.e-stat.go.jp/stat-search/files?page=1&layout=datalist&toukei=00200561&tstat=000000330001&cycle=7&year=20170&month=0&tclass1=000000330001&tclass2=000000330004&tclass3=000000330005&stat_infid=000031674338&result_back=1&tclass4val=0'
list_2018 = 'https://www.e-stat.go.jp/stat-search/files?page=1&layout=datalist&toukei=00200561&tstat=000000330001&cycle=7&year=20180&month=0&tclass1=000000330001&tclass2=000000330004&tclass3=000000330005&stat_infid=000031795468&result_back=1&tclass4val=0'
list_2019 = 'https://www.e-stat.go.jp/stat-search/files?page=1&layout=datalist&toukei=00200561&tstat=000000330001&cycle=7&year=20190&month=0&tclass1=000000330001&tclass2=000000330004&tclass3=000000330005&stat_infid=000031909555&result_back=1&tclass4val=0'
list_2020 = 'https://www.e-stat.go.jp/stat-search/files?page=1&layout=datalist&toukei=00200561&tstat=000000330001&cycle=7&year=20200&month=0&tclass1=000000330001&tclass2=000000330004&tclass3=000000330005&stat_infid=000032048835&result_back=1&tclass4val=0'
list_2021 = 'https://www.e-stat.go.jp/stat-search/files?page=1&layout=datalist&toukei=00200561&tstat=000000330001&cycle=7&year=20210&month=0&tclass1=000000330001&tclass2=000000330004&tclass3=000000330005&stat_infid=000032167631&result_back=1&tclass4val=0'
years.append(list_2000)
years.append(list_2001)
years.append(list_2002)
years.append(list_2003)
years.append(list_2004)
years.append(list_2005)
years.append(list_2006)
years.append(list_2007)
years.append(list_2008)
years.append(list_2009)
years.append(list_2010)
years.append(list_2011)
years.append(list_2012)
years.append(list_2013)
years.append(list_2014)
years.append(list_2015)
years.append(list_2016)
years.append(list_2017)
years.append(list_2018)
years.append(list_2019)
years.append(list_2020)
years.append(list_2021)

In [22]:
n = 2000
for year in years:
    driver = webdriver.Edge(executable_path='msedgedriver.exe')
    driver.get(year) # Googleを開く
    driver.maximize_window()

    dl_btn = driver.find_element_by_xpath("/html/body/div[1]/div/main/div[2]/section/div[2]/div/div/div[1]/section/section/div/div[1]/div/div[2]/a")
    dl_btn.click() # ダウンロードフォルダに格納される
    time.sleep(3)
    driver.quit()
    
    file_name = glob.glob("C:/Users/a_kih/Downloads/a401*.*")
    file_format = file_name[0].split('.')[1]
    temp_year = str(n)
    shutil.move(
        file_name[0],
        "./e-stat_data/data_{}.{}".format(temp_year, file_format)
    )
    n=n+1

c:\users\a_kih\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  This is separate from the ipykernel package so we can avoid doing imports until
c:\users\a_kih\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:7: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  import sys

In [13]:
allfiles = glob.glob("./e-stat_data/data*")

dfs = []
for file in allfiles:
    try:
        #print(file)
        temp = pd.read_excel(file, header=9)
        #print(temp.columns)
        file_year = file.split('_')[2]
        file_year = file_year.split('.')[0]
        temp = temp.rename(columns={'品   目   分   類':'品目分類'})
        temp = temp[['品目分類', 'Unnamed: 11']]
        temp = temp.rename(columns={'Unnamed: 11':'ポリ袋・ラップ（円/世帯)'})
        temp = temp[temp['品目分類']=='ポリ袋・ラップ']
        temp['年'] = file_year
        temp['世帯'] = "二人以上"
        temp = temp[['世帯', '年', 'ポリ袋・ラップ（円/世帯)']]
    except:
        #print(file)
        temp = pd.read_excel(file, header=9, engine='openpyxl')
        temp = temp.rename(columns={'品   目   分   類':'品目分類'})
        #print(temp.columns)
        file_year = file.split('_')[2]
        file_year = file_year.split('.')[0]
        temp = temp[['品目分類', '複数単位']]
        temp = temp.rename(columns={'複数単位':'ポリ袋・ラップ（円/世帯)'})
        temp = temp[temp['品目分類']=='ポリ袋・ラップ']
        temp['年'] = file_year
        temp['世帯'] = "二人以上"
        temp = temp[['世帯', '年', 'ポリ袋・ラップ（円/世帯)']]
    
    dfs.append(temp)
    #display(temp.head(5))
df = pd.concat(dfs)
df.head()

       世帯     年 ポリ袋・ラップ（円/世帯)
335  二人以上  2000          2695
335  二人以上  2001          2757
335  二人以上  2002          2835
335  二人以上  2003          2863
335  二人以上  2004          2822

In [14]:
df.head(30)

       世帯     年 ポリ袋・ラップ（円/世帯)
335  二人以上  2000          2695
335  二人以上  2001          2757
335  二人以上  2002          2835
335  二人以上  2003          2863
335  二人以上  2004          2822
337  二人以上  2005          2746
337  二人以上  2006          2863
337  二人以上  2007          2959
337  二人以上  2008          3069
337  二人以上  2009          3103
336  二人以上  2010          3098
336  二人以上  2011          3182
336  二人以上  2012          3128
336  二人以上  2013          3264
336  二人以上  2014          3408
346  二人以上  2015          3541
346  二人以上  2016          3631
346  二人以上  2017          3776
346  二人以上  2018          3828
346  二人以上  2019          4110
339  二人以上  2020       4569.00
339  二人以上  2021       4722.00

In [16]:
df.to_csv('data_result.csv', index=None, encoding='cp932')